### ISSUE TITLE
CUDA error running the code

### ISSUE THREAD

**Issue by dom-ce** [chengkai-liu/Mamba4Rec#4]
Hi authors,
I'm encountering this error when I run the code despite having configured everything correctly.
```
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
I'm attaching the log, a text file containing the output of the code execution, and two others corresponding respectively to the outputs of 'nvidia-smi' and 'nvcc -V'. Thank you in advance
[nvcc_output.txt](https://github.com/chengkai-liu/Mamba4Rec/files/14652924/nvcc_output.txt)
[nvidia-smi_output.txt](https://github.com/chengkai-liu/Mamba4Rec/files/14652925/nvidia-smi_output.txt)
[output.txt](https://github.com/chengkai-liu/Mamba4Rec/files/14652926/output.txt)
[Mamba4Rec-ml-1m-Mar-19-2024_16-11-53-ae14e3.log](https://github.com/chengkai-liu/Mamba4Rec/files/14652928/Mamba4Rec-ml-1m-Mar-19-2024_16-11-53-ae14e3.log)

**Comment by chengkai-liu** [comment]
It shows that [causal-conv1d](https://github.com/Dao-AILab/causal-conv1d) cannot work correctly in your setup. You can refer to the issues in the repositories of mamba and causal-conv1d. There are two issues with the same CUDA error:
https://github.com/state-spaces/mamba/issues/40
https://github.com/state-spaces/mamba/issues/85

I suggest discussing these errors within the Issues on the repository of [mamba](https://github.com/state-spaces/mamba/issues).

**Comment by dom-ce** [comment]
Thank you for the advice. I followed the guide showed in this [issue](https://github.com/state-spaces/mamba/issues/40) but uninstalling `causal-conv1d` which is optional to use `mamba-ssm`.
