### ISSUE TITLE
About the batch_size of item_emb

### ISSUE THREAD

**Issue by TBI805** [chengkai-liu/Mamba4Rec#6]
Hello! Thanks for your contributions!

In [mamba4rec.py](https://github.com/chengkai-liu/Mamba4Rec/blob/main/mamba4rec.py), I would like to know that why the batch_size of [item_emb] in line 63 is 1 when I debug on this point?

Actually, the [train_batch_size] in [config.yaml] is 2048, I‘m confused about this.

Would you please explain this matter to me in detail?

Thank you very much!
<img width="1091" alt="Snipaste_2024-04-09_21-05-59" src="https://github.com/chengkai-liu/Mamba4Rec/assets/34084035/3ad449a5-41fa-4c09-b591-f89f84d802cd">
<img width="1021" alt="Snipaste_2024-04-09_21-07-54" src="https://github.com/chengkai-liu/Mamba4Rec/assets/34084035/f09dc308-60e4-4492-bd7b-d645be771ca1">

**Comment by chengkai-liu** [comment]
Because the `get_flops` function calls the `predict` function, when you set a breakpoint in the `forward` function, the first stop is when the `get_flops` function (line 45, run.py) is entered. At this time, the model has not yet entered the training phase. If you continue to run, from (line 52, run.py), the next time at the `forward` breakpoint, the batch size will be 2048.

**Comment by TBI805** [comment]
OK, Thanks for your response!

I know that when mamba deal with the inputs, the dimension of input must be [B, L ,D], how you get the input for [1, 200]? Where the [batch_size] dimension(i.e. the 1) from the dataset? Why the batch_size is 1 rather than 2 or 3?

**Comment by TBI805** [comment]
OK, Thanks for your response!

But where does the [batch_size] dimension (i.e., 1) of the input data [item_emb] come from? Why is it 1 rather than 2 or 3? How you get this dimension from model loading and initialization?

**Comment by chengkai-liu** [comment]
You can set a breakpoint in get_flops, or look at the specific implementation of get_flops. You can also directly delete the get_flops function, which will not affect the result.

**Comment by TBI805** [comment]
I know that when the mamba deal with the input, the input size must be [B, L ,D], I understand where the L, D dimensions come from, but I'm confused as to where the B dimension comes from before the forward function.

**Comment by chengkai-liu** [comment]
For the data loading and batching process, you need to read the implementation details of [RecBole](https://github.com/RUCAIBox/RecBole).

**Comment by TBI805** [comment]
OK, I will check the implementation details, thanks!
