### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by hzau96yhz** [chengkai-liu/Mamba4Rec#7]
Hi! Good work!
What does the following line of code do?It seems that `self.gather_indexes` are not defined
https://github.com/chengkai-liu/Mamba4Rec/blob/d4d1fd64389f55684dfd62515ced4663f92a7476/mamba4rec.py#L65

**Comment by chengkai-liu** [comment]
`gather_indexes` is a function is the class of `SequentialRecommender`.
We import `SequentialRecommender` from RecBole: `from recbole.model.abstract_recommender import SequentialRecommender`.
